runtime: node010

env_dev: 
  SITE_MODE: 'dev'  

env_prod: 
 SITE_MODE: 'prod'
 

run_web: |
 #TODO: temp sess secret
 export SECRET_SESS_KEY=$RANDOM$RANDOM$RANDOM 
 node app.js

s: |
 exec rock run_web


test:


clean:



