runtime: node010

env_dev: 
  SITE_MODE: 'dev'  

env_prod: 
 SITE_MODE: 'prod'
 

run_web: |
 #TODO: temp sess secret
 export SECRET_SESS_KEY=$RANDOM$RANDOM$RANDOM 
 node app.js

s: |
 exec rock run_web


test:


clean:


db_load: | 
 echo "To import .sql file to db"
 mysql -uroot -p tessy < lib/sql/tessy_latest.sql


db_dump: |
 echo "To export db to .sql file"
 mysqldump -uroot -p tessy > lib/sql/tessy_latest.sql

